import React, { useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { Text, Input, Button } from 'react-native-elements';
import { COLORS } from './Colors';

const CreateToDoPrompt = (props) => {
  const { onSubmit } = props;
  const [summary, setSummary] = useState('');

  return (
    <View style={styles.modalWrapper}>
      <Text h4 style={styles.addItemTitle}>
        Product image and description with be generated by AI
      </Text>
      <Input
        placeholder="Product Name"
        onChangeText={(text) => setSummary(text)}
        autoCompleteType="off"
      />
       <Input
        placeholder="Product price"
        onChangeText={(text) => setSummary(text)}
        autoCompleteType="off"
      />
      <Button
        title="Save"
        buttonStyle={styles.saveButton}
        onPress={() => onSubmit({ summary })}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  modalWrapper: {
    width: 300,
    minHeight: 400,
    borderRadius: 4,
    alignItems: 'center',
  },
  addItemTitle: {
    margin: 20,
    fontSize:"14",
  },
  saveButton: {
    width: 280,
    backgroundColor: COLORS.primary,
  },
});

export { CreateToDoPrompt };
